apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-c8oforms-benchmarks
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: playwright-c8oforms-benchmarks
    spec:
      restartPolicy: Never
      containers:
        - name: playwright
          image: quay.io/replace-me/playwright-c8oforms-benchmarks:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: playwright-c8oforms-benchmarks
            - secretRef:
                name: playwright-c8oforms-benchmarks
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
